### ISSUE TITLE
Update peerDependencies to support React 17 and 18

### ISSUE THREAD

**Issue by danew** [feedback-fish/feedback-fish-react#21]
Currently this package only supports `react@^16.8.0`, since there isn't any breaking changes that will effect this package. 

I'll create a pull request shortly.

**Comment by kartikye** [comment]
Can this be released to npm?

**Comment by JClackett** [comment]
Yes please

**Comment by ben-foster** [comment]
+1

**Comment by kbyatnal** [comment]
the update has been merged but unfortunately the latest version hasn't been published to NPM for months (which doesn't exactly inspire confidence in a paid service...)

in the meantime, you can get around it by installing the merged commit instead

```
npm install --save git://github.com/feedback-fish/feedback-fish-react.git#bd77e8cf35cdc5873c821e9e168071047572abbb
```

**Comment by russ0133** [comment]
@kbyatnal I can not install it. Is something wrong?
![image](https://user-images.githubusercontent.com/26175960/217820211-ce8360dc-9a7c-4d69-979e-19179f433a71.png)

**Comment by il421** [comment]
+1

**Comment by stefee** [comment]
In case it helps anyone here, the newest version of npm supports overrides:

https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#overrides

```json
  "overrides": {
    "@feedback-fish/react": {
      "react": ">=17"
    }
  },
```

**Comment by jkelleyj** [comment]
Thanks everyone - This was just published to npm.
